# Generated by Django 3.2.8 on 2022-02-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC_1', '0002_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrtess_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
