# Generated by Django 3.2.8 on 2022-02-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TC_1', '0003_addrtess_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addrtess_info',
            new_name='Address_info',
        ),
    ]
